steps:
  - id: bootstrap-builder
    name: docker:22.06-rc-cli
    env:
      - "DOCKER_BUILDKIT=1"
      - "DOCKER_CLI_EXPERIMENTAL=enabled"
    entrypoint: "docker"
    args:
      - buildx
      - create
      - --name=buildkitd 
      - --node=buildkitd
      - --bootstrap
      - --buildkitd-flags='--containerd-worker-snapshotter=stargz'
      - --driver=docker-container
      - --platform=linux/amd64,linux/arm64
      - --driver-opt=image=moby/buildkit:master
      - --use
    waitFor:
      - "-"

  - id: cloud-datastore-emulator
    name: docker:22.06-rc-cli
    env:
      - "DOCKER_BUILDKIT=1"
      - "DOCKER_CLI_EXPERIMENTAL=enabled"
    entrypoint: "docker"
    args:
      - buildx
      - build
      - --platform=linux/amd64,linux/arm64
      - --pull
      - --build-arg=BUILDKIT_INLINE_CACHE=1
      - --build-arg=BUILDKIT_INLINE_BUILDINFO_ATTRS=1
      - --build-arg=OPENJDK_VERSION=${_OPENJDK_VERSION}
      - --build-arg=DATASTORE_EMULATOR_BUILD_NUMBER=${_DATASTORE_EMULATOR_BUILD_NUMBER}
      - --cache-from=type=registry,ref=amazoncorretto:${_OPENJDK_VERSION}
      - --label=org.opencontainers.image.revision=${COMMIT_SHA}
      - --output=type=registry
      - --target=cloud-datastore-emulator
      - --tag=asia-docker.pkg.dev/${PROJECT_ID}/gcp/cloud-datastore-emulator:${_DATASTORE_EMULATOR_BUILD_NUMBER}
      - --tag=us-docker.pkg.dev/${PROJECT_ID}/gcp/cloud-datastore-emulator:${_DATASTORE_EMULATOR_BUILD_NUMBER}
      - .
    waitFor:
      - "bootstrap-builder"

substitutions:
  _OPENJDK_VERSION: "11-alpine"
  _DATASTORE_EMULATOR_BUILD_NUMBER: "20220805142045"

tags:
  - "gcp.cloud-datastore-emulator"

options:
  dynamic_substitutions: true
  requestedVerifyOption: 'VERIFIED'

timeout: 900s  # 15min
